fixtures:
  repositories:
    apt: 'git://github.com/puppetlabs/puppetlabs-apt.git'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    systemd: 'git://github.com/camptocamp/puppet-systemd.git'
    zypprepo: 'git://github.com/voxpupuli/puppet-zypprepo.git'
    yumrepo_core:
      repo: 'git://github.com/puppetlabs/puppetlabs-yumrepo_core.git'
      puppet_version: '>= 6.0.0'