---
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.1
env:
  global:
    - BEAKER_PUPPET_COLLECTION=puppet6 PUPPET_GEM_VERSION="~> 6.0"
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    -
      env: CHECK=parallel_spec
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.4
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: instana
  password:
    secure: "J4Es+ij+CvqvV4RlBkwr14hZEGVgEVfqT3v/nXYaRyfYFSVMk6WW/nFkaAsLCou69sFxGUeQZUfX1fWEwZC4z6Rx7lOZoj+kvQj7xyho91bbvmXQtaGl/zUk2PzehQa8bAVB3Dgcgm0srXk62oHQRV5bFxrgqtgAjvfHhpjBWGf9t2HxXzWgAexXU8pM/8zdLCwZABHF6vxNdZCAYZmY5PcbbYzqWYWHUsWQZP6l5Xf6femHNG9X03OztCNprbE2GAQtp4PhzRKhuil9npXyDz/QZ7IgqzRU3JYvgEokPJBJoX8uC4QM7Rv0gSQyaiXyk2wiGplf4xZqKUM3fXlpd6SaEnDY9v9JcI9ZydLLScmjSzgBIlGrCia62En+vfOy4gQ8jbc2GiK2Neq5J34JsVbP+OUspncc3S7ZRX1YQimDIiE8UUwlB5ytQSB8WR11ckCfVmwQuVbQQQK1TlOL1l+tEjLmX1JKONOiX4vpOmuJE4iXd7OspY+j2llhlLWbQY8SZ2SgeI0daVgQYS54FTb4VKVpGDuAC47Oxw7ND2g6Pr325KmBiG4/o0dmXs8JjzzNWikJAazOTwaP9gndKhIOlodaSigL1x/++gOBAeukzzEyPTZYqjpmro7b0E4KoVWIvIkroXDXE4TFyLjjyGMoNWinYjcNdu3MCkfNkQQ="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
